### ISSUE TITLE
Regarding data generation 

### ISSUE THREAD

**Issue by Sunny-DV** [zongyi-li/fourier_neural_operator#32]
Hi, I am using this method for my college project. I am solving diffusion equation with some definite initial condition(u(x,0) = 0). I have solved it in python and now want to check in NN for accuracy and time consumption with final task being predict the result at specific location in time and space. 

I am using my initial condition for 256 grid as u(x,0) = 0 at every where and then save the u for every time step and try to learn it for some definite time interval and then predict the output as you used in fourier 2d_time. 
My concern is that i will create 256*20 point at t0 and make it (batch=20, point =256) and then again fro t1 and t2.... and then use it and same for 2d(20*256*256) at t0, t1, t2...
I just want to know i am right with the data generation? Please check and let me know. Thanks.

**Comment by zongyi-li** [comment]
Glad to hear that you want to use our method for your project. In our case, we have N (e.g. N=200) different realizations, each with different initializations or parameters. In your case, to my understanding there is only 1 realization, so you can set batch=1.

To get a decent performance you may need more data. For one realization, the model is likely to overfit. The neural operator is meant to learn a class of equation instead of one realization. It will be great to generate more data with different initializations.
