### ISSUE TITLE
About the comparative test

### ISSUE THREAD

**Issue by zmzhang97** [zongyi-li/fourier_neural_operator#41]
Hi, Zongyi Li,

This is a very good idea and very interesting! 
I want to ask you if there is any code for the comparison experiment in the experiment. Thank you very much!

**Comment by zongyi-li** [comment]
Thank you for your interest! We haven't decided to publish all the baseline methods, since they need a lot of clean-up. But if you don't mind, I can send you some of these baselines we have at hand. If that can be helpful, please let me know your email address. While I am preparing the code, please see these repositories:

For GKN and MKGN: https://github.com/zongyi-li/graph-pde
For UNets, Resnets, TF-Nets: https://github.com/Rose-STL-Lab/Turbulent-Flow-Net
The lowrank method is contained in this repostory (e.g. lowrank_2d.py)
I will send you the code for FCN, PCANN, and ROM once I gather them. Thanks!

**Comment by zmzhang97** [comment]
Looking forward to your follow-up work！ Thank you very much！

**Comment by zmzhang97** [comment]
Thanks! My email address: zmzhang97@outlook.com
