### ISSUE TITLE
Adding meta information about training data while training?

### ISSUE THREAD

**Issue by Tariq97** [zongyi-li/fourier_neural_operator#78]
Hi,

Hope you are doing well. Congratulations on this beautiful ML approach.
I would like to know how would you go about if you want to add meta data while training. By meta data, I mean for example viscosity while solving Navier stokes. You can generalize the model for different values of viscosity that way.
Have you thought about this? Meta data in a way influencing the R matrix?

Please let me know if you have any thoughts about it. I am working on a different problem but I need to input meta data in some way or another.

Thanks.

**Comment by zongyi-li** [comment]
Yes you can add meta data in several way

- directly at the input (extend/repear the scale input to an image)
- as a multiplier of the weight
- make the weight as hypernetworks

We didn't have the experiments since we only have 3 viscosity. I suppose it needs more viscosity values to generalize. In this case one can generate a dataset with randomly sampled viscosity.

**Comment by Tariq97** [comment]
Thank you for your reply Zongyi-Li.
I completely agree with your methods to include meta data.

However, I observed that adding directly at the input does not work very well. I am struggling to include weight multipliers or making the weight as hypernetworks.

Can you please provide a code on how you would do it by taking, say 4 meta data parameters for each data sample.

**Comment by zongyi-li** [comment]
Sorry for the delay. For example, this paper uses a hyper-network to address the meta parameters https://arxiv.org/pdf/2207.14366.pdf.
